name: test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.17.0
  curved_labeled_navigation_bar: ^2.0.5 
  firebase_core: ^2.14.0
  firebase_database: ^10.5.7
  url_launcher: ^6.1.10
  firebase_auth: ^4.3.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.3.5
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  sticky_headers: ^0.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true