// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyIMZ6DND6iZH2Ap0lltV_0PTxuHx0gOo',
    appId: '1:639746665410:web:58fbbf2a1f0b5424b7445b',
    messagingSenderId: '639746665410',
    projectId: 'child-monitor-ai',
    authDomain: 'child-monitor-ai.firebaseapp.com',
    databaseURL: 'https://child-monitor-ai-default-rtdb.firebaseio.com',
    storageBucket: 'child-monitor-ai.appspot.com',
    measurementId: 'G-1LC1GXWFWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0fzcELxtrQsrYi0AsSpyZFtuU87P8erA',
    appId: '1:639746665410:android:a25d5de32ef9bf43b7445b',
    messagingSenderId: '639746665410',
    projectId: 'child-monitor-ai',
    databaseURL: 'https://child-monitor-ai-default-rtdb.firebaseio.com',
    storageBucket: 'child-monitor-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJOMP-td9jHFhljLJX2zplEpe-wpOk9VM',
    appId: '1:639746665410:ios:975070173d3aba98b7445b',
    messagingSenderId: '639746665410',
    projectId: 'child-monitor-ai',
    databaseURL: 'https://child-monitor-ai-default-rtdb.firebaseio.com',
    storageBucket: 'child-monitor-ai.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJOMP-td9jHFhljLJX2zplEpe-wpOk9VM',
    appId: '1:639746665410:ios:975070173d3aba98b7445b',
    messagingSenderId: '639746665410',
    projectId: 'child-monitor-ai',
    databaseURL: 'https://child-monitor-ai-default-rtdb.firebaseio.com',
    storageBucket: 'child-monitor-ai.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyIMZ6DND6iZH2Ap0lltV_0PTxuHx0gOo',
    appId: '1:639746665410:web:56c4f83e447c6ee2b7445b',
    messagingSenderId: '639746665410',
    projectId: 'child-monitor-ai',
    authDomain: 'child-monitor-ai.firebaseapp.com',
    databaseURL: 'https://child-monitor-ai-default-rtdb.firebaseio.com',
    storageBucket: 'child-monitor-ai.appspot.com',
    measurementId: 'G-1V02Z8N5KT',
  );
}
